apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "weather-bot.fullname" . }}-migration"
  labels:
    app.kubernetes.io/name: "{{ include "weather-bot.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "weather-bot.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["./main"]
          args: ["migrate"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.auth.existingSecret }}
                  key: db_url
            # 他の必要な環境変数をここに追加
      restartPolicy: Never
  backoffLimit: {{ .Values.migration.backoffLimit }}
