apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "weather-bot.fullname" . }}-seed-{{ .Release.Revision }}"
  labels:
    app.kubernetes.io/name: "{{ include "weather-bot.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "weather-bot.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: seed
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          workingDir: /root/
          command: ["./weather-bot"]
          args: ["seed"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: db_url
      restartPolicy: Never
  backoffLimit: {{ .Values.migration.backoffLimit }}
