services:
  client:
    build: ./client/my-nuxt-app
    volumes:
      - ./client/my-nuxt-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todos?sslmode=disable
    depends_on:
      - db
      - migrate

  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: