# weather-bot/values.yaml

replicaCount: 2

image:
  repository: isshinfunada/weather-bot  # Docker Hubのリポジトリ名
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: paraponerainy.duckdns.org
      paths:
        - path: /webhook
          pathType: Prefix
  tls: []  # TLS設定が必要な場合はここに追加

env:
  - name: DB_URL
    value: "postgresql://username:password@postgres.weather-bot.svc.cluster.local:5432/weather-bot?sslmode=disable"
  - name: LINE_CHANNEL_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: line-api-secret
        key: access_token
  - name: LINE_CHANNEL_SECRET
    valueFrom:
      secretKeyRef:
        name: line-api-secret
        key: channel_secret

serviceAccount:
  create: true
  # name: "" # 必要に応じてカスタム名を指定
  automount: true
  # annotations: {} # 必要に応じてアノテーションを追加

autoscaling:
  enabled: false  # HPAを有効にする場合は true に変更
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80  # CPU使用率のターゲット
  targetMemoryUtilizationPercentage: 70  # メモリ使用率のターゲット